name: 'Onboardbase'
description: 'A Github Action to inject secrets from Onboardbase into a Github runner'
inputs:
  apikey:  
    description: 'The Onboardbase APIKey'
    required: true
  passcode:  
    description: 'The Onboardbase passcode'
    required: true
  project:  
    description: 'The project to fetch secrets from'
    required: true
  environment:  
    description: 'The environment to fetch secrets from'
    required: true
# outputs:
#   secrets:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - uses: mikefarah/yq@master
      with:
        cmd: |
          touch file.yaml
          yq -i '.apiKey = "${{ inputs.apikey }}"' .onboardbase.yaml
          yq -i '.passCode = "${{ inputs.passcode }}"' .onboardbase.yaml
          yq -i '.setup.project = "${{ inputs.project }}"' .onboardbase.yaml
          yq -i '.setup.environment = "${{ inputs.environment }}"' .onboardbase.yaml
    
    - run: cat .onboardbase.yaml
      shell: bash

    - run: |
        # Download the deb
        wget https://onboardbase-cli.fra1.digitaloceanspaces.com/apt/onboardbase-latest.deb
        sudo dpkg -i ./onboardbase-latest.deb
        onboardbase --version
      shell: bash
  
    