name: 'Onboardbase'
description: 'A Github Action to inject secrets from Onboardbase into a Github runner'
inputs:
  apikey:  
    description: 'The Onboardbase APIKey'
    required: true
  passcode:  
    description: 'The Onboardbase passcode'
    required: true
  project:  
    description: 'The project to fetch secrets from'
    required: true
  environment:  
    description: 'The environment to fetch secrets from'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'