name: Test workflow

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Fetch secrets
        id: fetch-secrets
        uses: Onboardbase/onboardbase-action@v6.0.4
        with:
          apikey: NFUG7BEVU73FEM6NKR4NK3 #${{secrets.APIKEY}}
          passcode: passcode #${{secrets.PASSCODE}}
          project: test_project
          environment: development

      - name: Use secrets
        # Output should be: The secret value is: https://test.com
        run: echo The secret value is: ${{ steps.fetch-secrets.outputs.REDIS_HOST }}