name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Fetch secrets
        id: fetch-secrets
        uses: Onboardbase/onboardbase-action@v0.0.5
        with:
          apikey: ${{secrets.APIKEY}}
          passcode: ${{secrets.PASSCODE}}
          project: test
          environment: development

      - name: Use secrets
        run: echo "The time was ${{ steps.fetch-secrets.outputs.secrets }}"