name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets
        id: fetch-secrets
        uses: Onboardbase/onboardbase-action@v6.0.7
        with:
          apikey: ${{secrets.APIKEY}}
          passcode: ${{secrets.PASSCODE}}
          project: test_project
          environment: development
      - name: Use secrets
        # Output should be: The secret value is: https://test.com
        run: echo ::add-mask::${{ steps.fetched-secrets.outputs.REDIS_HOST }}
