name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets
        id: fetch-secrets
        uses: Onboardbase/onboardbase-action@v6.0.7
        with:
          apikey: ${{secrets.APIKEY}}
          passcode: ${{secrets.PASSCODE}}
          project: test_project
          environment: development
      - name: create mask
        id: masked-secrets
        run: |
          echo ::add-mask::${{steps.fetch-secrets.outputs}}
      - name: Use secrets
        # Output should be: The secret value is: https://test.com
        run: "echo 'The secret value is: ${{ steps.masked-secrets.outputs.REDIS_HOST }}'"
