name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets
        id: fetch-secrets
        uses: Onboardbase/onboardbase-action@v6.0.8
        with:
          apikey: ${{secrets.APIKEY}}
          passcode: ${{secrets.PASSCODE}}
          project: test_project
          environment: development

      - id: masks-a-secret
        run: |
          the_secret=$steps.fetch-secrets.outputs.REDIS_HOST
          echo "::add-mask::$the_secret"
          echo "::set-output name=REDIS_HOST::$the_secret"
      - run: |
          echo "the secret number is ${{ steps.masks-a-secret.outputs.REDIS_HOST }}"
